// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  var arrayToSet;

  arrayToSet = function(arr) {
    "Takes a list of things and puts into an object so that testing for existence is faster";
    var obj, set, _i, _len;
    set = {};
    for (_i = 0, _len = arr.length; _i < _len; _i++) {
      obj = arr[_i];
      set[obj] = true;
    }
    return set;
  };

  module.exports = arrayToSet;

}).call(this);
